export const koreanToEnglishMap = {
  "서울": "Seoul",
  "인천": "Incheon",
  "부산": "Busan",
  "대구": "Daegu",
  "대전": "Daejeon",
  "광주": "Gwangju",
  "울산": "Ulsan",
  "세종": "Sejong",
  "수원": "Suwon",
  "창원": "Changwon",
  "전주": "Jeonju",
  "청주": "Cheongju",
  "춘천": "Chuncheon",
  "원주": "Wonju",
  "강릉": "Gangneung",
  "속초": "Sokcho",
  "포항": "Pohang",
  "진주": "Jinju",
  "거제": "Geoje",
  "여수": "Yeosu",
  "남원": "Namwon",
  "김해": "Gimhae",
  "안동": "Andong",
  "목포": "Mokpo",
  "군산": "Gunsan",
  "제주": "Jeju",
  "양양": "Yangyang",
  "통영": "Tongyeong",
  "양산": "Yangsan",
  "의정부": "Uijeongbu",
  "뉴욕": "New York",
  "로스앤젤레스": "Los Angeles",
  "시카고": "Chicago",
  "필라델피아": "Philadelphia",
  "샌디에이고": "San Diego",
  "댈러스": "Dallas",
  "런던": "London",
  "파리": "Paris",
  "베를린": "Berlin",
  "마드리드": "Madrid",
  "로마": "Rome",
  "빈": "Vienna",
  "암스테르담": "Amsterdam",
  "브뤼셀": "Brussels",
  "취리히": "Zurich",
  "코펜하겐": "Copenhagen",
  "스톡홀름": "Stockholm",
  "모스크바": "Moscow",
  "두바이": "Dubai",
  "카이로": "Cairo",
  "예루살렘": "Jerusalem",
  "베이징": "Beijing",
  "상하이": "Shanghai",
  "광저우": "Guangzhou",
  "도쿄": "Tokyo",
  "오사카": "Osaka",
  "교토": "Kyoto",
  "방콕": "Bangkok",
  "하노이": "Hanoi",
  "호치민": "Ho Chi Minh City",
  "마닐라": "Manila",
  "싱가포르": "Singapore",
  "시드니": "Sydney",
  "토론토": "Toronto",
  "밴쿠버": "Vancouver",
  "타이베이" : "Taipei",
  "홍콩": "Hong Kong"
};

export const convertToEnglish = (input) => {
  const name = input.trim();
  const mapResult = koreanToEnglishMap[name];
  if (mapResult) return mapResult;

  return name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
};
